schema_version: 1

context:
  name: azure-mgmt-billing
  version: 6.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-billing-${{ version }}.zip
  sha256: d4f5c5a4188a456fe1eb32b6c45f55ca2069c74be41eb76921840b39f2f5c07f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1<2.0
    - azure-mgmt-core >=1.2.0,<2.0
    - msrest >=0.6.21

tests:
  - python:
      imports:
        - azure.mgmt.billing
        - azure.mgmt.billing.aio
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Billing Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
